name: CI - Selenium Tests + Publish Report

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable || \
            (wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
             && sudo apt-get install -y ./google-chrome-stable_current_amd64.deb)

      - name: Run tests
        run: mvn -B test

      - name: Upload Extent report (optional download)
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: docs/reports/*.html

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs